# Generated by Django 3.0.7 on 2020-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profname',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='ユーザーネーム'),
        ),
        migrations.AddField(
            model_name='user',
            name='proftext',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='プロフィール'),
        ),
    ]
