# Generated by Django 3.0.7 on 2020-06-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200612_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ユーザーネーム'),
        ),
    ]
