# Generated by Django 3.0.7 on 2020-07-07 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot_app', '0002_blog_news_robot_evaluation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='summary',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
