# Generated by Django 3.0.7 on 2020-07-03 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot_app', '0002_robot_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot_evaluation',
            name='robot_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='robot_name'),
        ),
        migrations.AlterField(
            model_name='robot_evaluation',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default='3', verbose_name='ロボットスコア'),
        ),
        migrations.AlterUniqueTogether(
            name='robot_evaluation',
            unique_together={('robot_name', 'user_name')},
        ),
        migrations.RemoveField(
            model_name='robot_evaluation',
            name='robot_id',
        ),
    ]
