# Generated by Django 3.0.7 on 2020-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0003_auto_20200707_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robot_evaluation',
            unique_together=set(),
        ),
    ]
