# Generated by Django 3.0.7 on 2020-07-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0005_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='celebrity',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='interest',
            new_name='question',
        ),
    ]
