# Generated by Django 3.0.7 on 2020-07-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0006_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='user_name',
        ),
    ]
