FROM python:3.8.3

RUN pip3 install --upgrade pip

COPY ./web/requirements.txt /code/
RUN pip3 install -r /code/requirements.txt

COPY ./src/ /code/
COPY ./web/run-my-app.sh /code/

EXPOSE 8001
WORKDIR /code/

ARG DUID
ARG DGID



# uwsgi 用のログパスを追加
RUN mkdir /var/log/uwsgi/
RUN chown -R $DUID:$DGID /var/log && \
    chown -R $DUID:$DGID /code

USER $DUID
